CREATE DATABASE db-concesionario;

USE db-concesionario;

CREATE TABLE vehiculos (
  id INT(11) NOT NULL AUTO_INCREMENT,
  modelo VARCHAR(100) NOT NULL,
  precio NUMERIC(10,2) NOT NULL,
  imagen VARCHAR(255) NOT NULL,
  color VARCHAR(15) DEFAULT NULL,
  potencia INT(3) DEFAULT NULL,
  CONSTRAINT PK_VEH PRIMARY KEY (id) 
);

CREATE TABLE compras (
  id INT(11) NOT NULL AUTO_INCREMENT,
  vehiculo_id INT(11) DEFAULT NULL,
  nombre VARCHAR(100) DEFAULT NULL,
  email VARCHAR(100) DEFAULT NULL,
  telefono INT(9) DEFAULT NULL,
  mensaje VARCHAR(200) DEFAULT NULL,
  fecha TIMESTAMP NOT NULL DEFAULT current_timestamp(),
  CONSTRAINT PK_COMPRA PRIMARY KEY (id),
  CONSTRAINT FK_VEH FOREIGN KEY (vehiculo_id) REFERENCES vehiculos(id) ON DELETE CASCADE ON UPDATE CASCADE
);